language: node_js

addons:
  chrome: stable

sudo: required

node_js:
  - '12'

before_install:
  - 'sudo chown root /opt/google/chrome/chrome-sandbox'
  - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

script:
  - npm run build
  - npm run test
